/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_CONFIDENTIALPACKAGESPECIFICATION_ARGS_H
#define EDGER8R_CONFIDENTIALPACKAGESPECIFICATION_ARGS_H

/**** User includes. ****/
/* There were no user includes. */

/**** User defined types in EDL. ****/
#ifndef EDGER8R_ENUM_OPTEE_CONFIDENTIALPACKAGEMANAGERUUID
#define EDGER8R_ENUM_OPTEE_CONFIDENTIALPACKAGEMANAGERUUID
typedef enum optee_ConfidentialPackageManagerUUID
{
    CPM_UUID_P0 = 3552951228,
    CPM_UUID_P1 = 44461,
    CPM_UUID_P2 = 4587,
    CPM_UUID_P3 = 189,
    CPM_UUID_P4 = 37,
    CPM_UUID_P5 = 67,
    CPM_UUID_P6 = 98,
    CPM_UUID_P7 = 0,
    CPM_UUID_P8 = 46,
    CPM_UUID_P9 = 39,
    CPM_UUID_P10 = 73
} optee_ConfidentialPackageManagerUUID;
#endif

#endif // EDGER8R_CONFIDENTIALPACKAGESPECIFICATION_ARGS_H
