[package]
name = "cpk"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpk-sys = { path = "../cpk-sys" }
thiserror = "1.0.20"
serde = "1.0.126"
serde_json = "1.0.64"
bincode = "1.3.3"
