[package]
name = "cpk-sys"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
env = "0.0.0"
bindgen = "0.53.1"
cc = "1.0"

[features]
cpm-simulator = []
